# Generated by Django 5.0.14 on 2025-11-10 19:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company/Organization name', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, help_text='Expected deal value in EUR', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('company_size', models.IntegerField(help_text='Number of employees', validators=[django.core.validators.MinValueValidator(1)])),
                ('industry', models.CharField(choices=[('tech', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('other', 'Other')], default='other', max_length=20)),
                ('urgency', models.CharField(choices=[('immediately', 'Immediately'), ('this_week', 'This Week'), ('this_month', 'This Month'), ('later', 'Later')], default='later', max_length=20)),
                ('score', models.IntegerField(default=0, help_text='Automatically calculated lead score (0-100)', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='The tenant this lead belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.tenant')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['tenant', '-score'], name='leads_lead_tenant__12adc3_idx'), models.Index(fields=['tenant', '-created_at'], name='leads_lead_tenant__be44ed_idx')],
            },
        ),
    ]
